services:
  database:
    image: codenotary/immudb:latest
    ports:
      - 3322:3322 #GRPC
      - 9497:9497 #TODO Metrics?
      - 8080:8080 #HTTP
      - 5432:5432 #TODO CLarify
    networks:
      - back-tier

  koala:
    image: ghcr.io/mymichu/koala:latest
    ports:
      - 8002:8002
    networks:
      - back-tier
    environment:
      IMMUDB_HOST: "database"

configs:
  httpd-config:
    external: true

secrets:
  server-certificate:
    external: true

networks:
  back-tier: {}
