name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      FORCE_COLOR: 1
      REMOTE_APP_CACHE: ghcr.io/mymichu/koala:cache
      REMOTE_BUILD_CACHE: ghcr.io/mymichu/koala-build:cache
      REMOTE_INTEGRATION_TEST_CACHE: ghcr.io/mymichu/koala-int-test:cache
      REMOTE_SYSTEM_TEST_CACHE: ghcr.io/mymichu/koala-system-test:cache
    steps:
    - uses: actions/checkout@v3

    - name: Put back the git branch into git (Earthly uses it for tagging)
      run: |
        branch=""
        if [ -n "$GITHUB_HEAD_REF" ]; then
          branch="$GITHUB_HEAD_REF"
        else
          branch="${GITHUB_REF##*/}"
        fi
        git checkout -b "$branch" || true
    - name: Download latest earthly
      run: "sudo /bin/sh -c 'wget https://github.com/earthly/earthly/releases/download/v0.6.29/earthly-linux-amd64 -O /usr/local/bin/earthly && chmod +x /usr/local/bin/earthly'"
    
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.TOKEN_WRITE_PACKAGE_MYMICHU }}

    - name: Run install dependency
      run: earthly --ci --remote-cache=${{ env.REMOTE_BUILD_CACHE }} --push +install

    - name: Run check Code Qality
      run: earthly --ci --remote-cache=${{ env.REMOTE_BUILD_CACHE }} +check

    - name: Run build
      run: earthly --ci --remote-cache=${{ env.REMOTE_BUILD_CACHE }} +build

    - name: Run integration test
      run: earthly --ci -P --remote-cache=${{ env.REMOTE_INTEGRATION_TEST_CACHE }} --push +test

    - name: integrate koala in docker image
      run: earthly --remote-cache=${{ env.REMOTE_APP_CACHE }} +docker-app

    - name: Run System test
      run: earthly --ci -P --remote-cache=${{ env.REMOTE_SYSTEM_TEST_CACHE }} --push +sys-test

    - name: Publish Docker Image
      run: earthly --remote-cache=${{ env.REMOTE_APP_CACHE }} --push +docker-app
      if:  github.ref == 'refs/heads/main'
      
